version : "3"
services:
  app:
    build: .
    restart: always
    env_file:
      - .config/config.env
    volumes:
      - ./tmp/dummy:/ssm/tmp/dummy

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=default_discord
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
